name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run tests
      run: go test -v ./...

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Extract release notes
      id: extract_notes
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }}
        NOTES_FILE="RELEASE_NOTES_${VERSION}.md"

        if [ -f "$NOTES_FILE" ]; then
          echo "notes_file=$NOTES_FILE" >> $GITHUB_OUTPUT
          echo "has_notes=true" >> $GITHUB_OUTPUT
        else
          echo "has_notes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body_path: ${{ steps.extract_notes.outputs.has_notes == 'true' && steps.extract_notes.outputs.notes_file || '' }}
        draft: false
        prerelease: false
        generate_release_notes: ${{ steps.extract_notes.outputs.has_notes == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger pkg.go.dev update
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }}
        curl -f "https://proxy.golang.org/github.com/julianshen/gonp-datareader/@v/${VERSION}.info" || true
